version: '3.9'

services:
  media-checker-cpu:
    build:
      context: .
      dockerfile: compose/Dockerfile.cpu
    container_name: media-checker-cpu
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

  media-checker-gpu:
    build:
      context: .
      dockerfile: compose/Dockerfile.gpu
    container_name: media-checker-gpu
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - .env
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  postgres:
    image: postgres:14
    container_name: media-checker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_checker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
